% COVERTREE_DISTANCES definitions
COVERTREE_DISTANCE_EUCLIDEAN                                    = int32(0);
COVERTREE_DISTANCE_EUCLIDEAN_ABS_VALUES                         = int32(1);
COVERTREE_DISTANCE_TRANSLATION_INVARIANT_2D                     = int32(2);
COVERTREE_DISTANCE_EUCLIDEAN_ABS_FFT_2D                         = int32(3);
COVERTREE_DISTANCE_ROTATION_INVARIANT_2D                        = int32(4);
COVERTREE_DISTANCE_TRANSLATION_ROTATION_INVARIANT_2D            = int32(5);
COVERTREE_DISTANCE_TRANSLATION_ROTATION_ISODILATION_INVARIANT   = int32(6);
COVERTREE_DISTANCE_RMSD                                         = int32(7);
COVERTREE_DISTANCE_FUBINISTUDY                                  = int32(8);

% COVERTREE_CLASSNAME definitions
COVERTREE_CLASSNAME_VECTOR          = int32(0);
COVERTREE_CLASSNAME_IMAGE           = int32(1);
COVERTREE_CLASSNAME_MOLECULARSTATE  = int32(2);
